# This workflow build a .NET project according to the github official .NET action 

name: .NET

on:
    push:
        branches: ["Workflow"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET 8.0
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --configuration Release --no-restore
        - name: Using artifacts | Upload build artifacts
          uses: actions/upload-artifact@v4.6.2
          with:
            name: dev.mssp
            path: bin/Release/net8.0/

        - name: Download artifact
          uses: actions/download-artifact@v4.3.0
          with:
            name: dev.mssp
            path: publish
        
        - name: Copy artifact to the server
          uses: appleboy/scp-action@v1
          with:
             host: ${{ secrets.FTP_SERVER }}
             username: ${{ secrets.FTP_USERNAME }}
             password: ${{ secrets.FTP_PASSWORD }}
             port: 22
             source: publish/*
             target: /var/www/html/mssp/

            